# Generated by Django 5.1.7 on 2025-08-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="form_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="instagram_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="lead_type",
            field=models.CharField(
                choices=[
                    ("newsletter", "Newsletter Subscriber"),
                    ("contact_form", "Contact Form"),
                    ("landing_page", "Landing Page"),
                    ("giveaway", "Giveaway"),
                ],
                default="newsletter",
                max_length=100,
            ),
        ),
    ]
