# Generated by Django 5.1.7 on 2025-05-19 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allergens", "0001_initial"),
        ("carts", "0001_initial"),
        ("products", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitemboxflavorselection",
            name="box_customization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flavor_selections",
                to="carts.cartitemboxcustomization",
            ),
        ),
        migrations.CreateModel(
            name="CartItemPackCustomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selection_type",
                    models.CharField(
                        choices=[
                            ("RANDOM", "Random"),
                            ("PICK_AND_MIX", "Pick and Mix"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "allergens",
                    models.ManyToManyField(blank=True, to="allergens.allergen"),
                ),
                (
                    "cart_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_customization",
                        to="carts.cartitem",
                    ),
                ),
                (
                    "chocolate_bark",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chocolate_bark_pack_customizations",
                        to="products.product",
                    ),
                ),
                (
                    "gift_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_card_pack_customizations",
                        to="products.product",
                    ),
                ),
                (
                    "hot_chocolate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hot_chocolate_pack_customizations",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cartitemboxflavorselection",
            name="pack_customization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flavor_selections",
                to="carts.cartitempackcustomization",
            ),
        ),
    ]
