# Generated by Django 5.1.7 on 2025-09-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="pickup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="pickup_time",
            field=models.CharField(blank=True, null=True),
        ),
    ]
