# Generated by Django 5.1.7 on 2025-06-11 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_alter_cartitemboxflavorselection_box_customization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitemboxflavorselection",
            name="pack_customization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flavor_selections_pack",
                to="carts.cartitempackcustomization",
            ),
        ),
    ]
