# Generated by Django 5.2.6 on 2025-09-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_alter_cartitemboxflavorselection_pack_customization"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="pickup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="pickup_time",
            field=models.CharField(blank=True, null=True),
        ),
    ]
