# Generated by Django 5.2.6 on 2025-10-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_cart_pickup_date_cart_pickup_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitemboxcustomization",
            name="selection_type",
            field=models.CharField(
                blank=True,
                choices=[("RANDOM", "Random"), ("PICK_AND_MIX", "Pick and Mix")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cartitempackcustomization",
            name="selection_type",
            field=models.CharField(
                choices=[("RANDOM", "Random"), ("PICK_AND_MIX", "Pick and Mix")],
                default="RANDOM",
                max_length=20,
            ),
        ),
    ]
