# Generated by Django 5.2.6 on 2026-02-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0005_alter_cartitemboxcustomization_selection_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="selected_custom_option_key",
            field=models.CharField(
                blank=True,
                help_text="Identifier of the selected custom option from the product",
                max_length=255,
                null=True,
            ),
        ),
    ]
