# Generated by Django 5.1.5 on 2025-02-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsent",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
    ]
