# Generated by Django 5.1.5 on 2025-02-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0002_emailsent_is_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtype",
            name="name",
            field=models.CharField(
                choices=[
                    ("newsletter", "Newsletter"),
                    ("contact", "Contact"),
                    ("order_paid", "Order Paid"),
                    ("non_payed_order", "Non Payed Order"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
