# Generated by Django 5.1.7 on 2025-06-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0003_alter_emailtype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtype",
            name="name",
            field=models.CharField(
                choices=[
                    ("newsletter", "Newsletter"),
                    ("contact", "Contact"),
                    ("order_paid", "Order Paid"),
                    ("non_payed_order", "Non Payed Order"),
                    ("order_shipping", "Order Shipping"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
