# Generated by Django 5.1.7 on 2025-06-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("mails", "0004_alter_emailtype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtype",
            name="name",
            field=models.CharField(
                choices=[
                    ("newsletter", "Newsletter"),
                    ("contact", "Contact"),
                    ("order_paid", "Order Paid"),
                    ("non_payed_order", "Non-Paid Order"),
                    ("order_shipping", "Order Shipping"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="emailsent",
            index=models.Index(
                fields=["content_type", "object_id", "email_type"],
                name="mails_email_content_a33413_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailsent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_test", False)),
                fields=("content_type", "object_id", "email_type"),
                name="unique_nontest_email_per_object",
            ),
        ),
    ]
