# Generated by Django 5.1.7 on 2025-06-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0005_alter_emailtype_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="emailsent",
            name="unique_nontest_email_per_object",
        ),
    ]
