# Generated by Django 5.1.7 on 2025-08-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0006_remove_emailsent_unique_nontest_email_per_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtype",
            name="name",
            field=models.CharField(
                choices=[
                    ("newsletter", "Newsletter"),
                    ("contact", "Contact"),
                    ("order_paid", "Order Paid"),
                    ("non_payed_order", "Non-Paid Order"),
                    ("order_shipping", "Order Shipping"),
                    ("review_request", "Review Request"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
