# Generated by Django 5.2.6 on 2025-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flavours", "0002_alter_flavour_options_remove_flavour_image_webp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flavour",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flavour",
            name="featured_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
