# Generated by Django 5.2.17 on 2026-09-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flavours", "0003_flavour_featured_flavour_featured_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="flavour",
            name="story",
            field=models.TextField(blank=True, default=""),
        ),
    ]
