# Generated by Django 5.1.7 on 2025-06-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0004_alter_shippingoption_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingoption",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shippingoption",
            name="disabled_reason",
            field=models.TextField(blank=True),
        ),
    ]
