# Generated by Django 5.2.17 on 2026-09-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0005_shippingoption_disabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingoption",
            name="guaranteed",
            field=models.BooleanField(
                default=False,
                help_text="True only for services the carrier contractually guarantees, like Royal Mail Special Delivery. Everything else is an estimate, and the checkout must word it that way — most orders are gifts for a fixed date, so the difference matters to the customer.",
            ),
        ),
    ]
