# Generated by Django 5.1.5 on 2025-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
