# Generated by Django 5.1.7 on 2025-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_shipping_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitsSold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=64)),
                ("date", models.DateField()),
                ("units_sold", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-created"],
                "unique_together": {("source", "date")},
            },
        ),
    ]
