# Generated by Django 5.1.7 on 2025-08-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_set_unitsold_sourcefk"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="unitssold",
            unique_together={("source_fk", "date")},
        ),
        migrations.RemoveField(
            model_name="unitssold",
            name="source",
        ),
    ]
