# Generated by Django 5.1.7 on 2025-08-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_unitssold_unique_together_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="unitssold",
            index=models.Index(
                fields=["source_fk", "date"], name="orders_unit_source__23bc03_idx"
            ),
        ),
    ]
