# Generated by Django 5.1.5 on 2025-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="preorder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="preorder_finish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="preorder_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
