# Generated by Django 5.1.7 on 2025-05-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_preorder_product_preorder_finish_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["category__id", "base_price"]},
        ),
    ]
