# Generated by Django 5.1.7 on 2025-05-25 12:58

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Main product image",
                null=True,
                storage=storages.backends.s3.S3Storage(location="media"),
                upload_to="flavours",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="image_webp",
            field=models.ImageField(
                blank=True,
                help_text="WebP version of main image",
                null=True,
                upload_to="products/images/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image (JPEG)",
                null=True,
                upload_to="products/thumbnails/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="thumbnail_webp",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image (WebP)",
                null=True,
                upload_to="products/thumbnails/%Y/%m/",
            ),
        ),
    ]
