# Generated by Django 5.1.7 on 2025-06-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productcategory_image_productcategory_image_webp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ["order", "-created"]},
        ),
        migrations.AddField(
            model_name="productcategory",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
