# Generated by Django 5.2.6 on 2025-10-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_productcategory_options_productcategory_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="can_pick_allergens",
            field=models.BooleanField(default=False),
        ),
    ]
