# Generated by Django 5.2.6 on 2026-01-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_can_pick_allergens"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="alert_message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="pickup_from_date",
            field=models.DateField(
                blank=True,
                help_text="Date from which pickup becomes available",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pickup_only",
            field=models.BooleanField(
                default=False, help_text="Product can only be picked up in person"
            ),
        ),
    ]
