# Generated by Django 5.2.6 on 2026-02-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_alert_message_product_pickup_from_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="custom_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Flexible list of custom options for this product",
            ),
        ),
    ]
