# Generated by Django 5.2.17 on 2026-09-21 17:00

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_product_compare_at_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="badge_active",
            field=models.BooleanField(
                default=False,
                help_text="Show the badge. Turning this off keeps the wording for later.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="badge_color",
            field=models.CharField(
                choices=[
                    ("slate", "Slate"),
                    ("green", "Green"),
                    ("amber", "Amber"),
                    ("rose", "Rose"),
                    ("violet", "Violet"),
                ],
                default="slate",
                help_text="Badge background. The five presets are the ones that stay readable with white text; a free colour is how you end up with white on yellow.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="badge_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Short label shown on the product card, e.g. "Best seller".',
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Give this product the full width of the grid on phones. Needs a wide image, or it falls back to a normal card.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="indulgence_image",
            field=models.ImageField(
                blank=True,
                help_text="Image shown when this box is made into an indulgence pack",
                null=True,
                storage=storages.backends.s3.S3Storage(location="media"),
                upload_to="products/indulgence",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="indulgence_image_webp",
            field=models.ImageField(
                blank=True,
                help_text="WebP version of the indulgence image",
                null=True,
                upload_to="products/indulgence/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="wide_image",
            field=models.ImageField(
                blank=True,
                help_text="Wide (roughly 2:1) image for the featured card",
                null=True,
                storage=storages.backends.s3.S3Storage(location="media"),
                upload_to="products/wide",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="wide_image_webp",
            field=models.ImageField(
                blank=True,
                help_text="WebP version of the wide image",
                null=True,
                upload_to="products/wide/%Y/%m/",
            ),
        ),
    ]
