# Generated by Django 5.2.17 on 2026-10-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_product_badge_active_product_badge_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fixed_dispatch_date",
            field=models.DateField(
                blank=True,
                help_text="Post this product on this exact day (e.g. an advent calendar batch). A cart containing it cannot be collected in store and cannot pick its own posting date. Clear it to go back to normal.",
                null=True,
            ),
        ),
    ]
